from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
MAIN = ROOT / 'app/src/main/java/com/rww/wetypeswipe/MainHook.java'
GRADLE = ROOT / 'gradle.properties'
RUNTIME = ROOT / 'app/src/main/java/com/rww/wetypeswipe/KeyboardRuntimeState.java'
TEST = ROOT / 'app/src/test/java/com/rww/wetypeswipe/KeyboardRuntimeStateTest.java'
NOTES = ROOT / 'TEST_NOTES_v1.11.9-test3.md'


def replace_once(text, old, new, label):
    if text.count(old) != 1:
        raise SystemExit(f'{label}: expected 1 occurrence, found {text.count(old)}')
    return text.replace(old, new, 1)

text = MAIN.read_text(encoding='utf-8')
text = replace_once(text,
    'logInfo("v1.11.9-test2 entered target package; phase-1 refactor + live dark-mode refresh enabled");',
    'logInfo("v1.11.9-test3 entered target package; hot-path performance optimizations enabled");',
    'version log')

text = replace_once(text,
'''    private volatile long nativeSingleKeyPaintSignature = Long.MIN_VALUE;\n    private volatile int lastResolvedNightMode = Configuration.UI_MODE_NIGHT_UNDEFINED;\n''',
'''    private volatile long nativeSingleKeyPaintSignature = Long.MIN_VALUE;\n    private volatile int lastResolvedNightMode = Configuration.UI_MODE_NIGHT_UNDEFINED;\n    private volatile int liveNightMode = Configuration.UI_MODE_NIGHT_UNDEFINED;\n    private volatile WeakReference<View> runtimeKeyboardRef = new WeakReference<>(null);\n    private volatile KeyboardRuntimeState runtimeKeyboardState;\n    private final ConcurrentHashMap<Class<?>, Boolean> keyboardDrawPreparedClasses = new ConcurrentHashMap<>();\n    private volatile long nativeSingleKeyNextResolveAtMs;\n''',
    'runtime fields')

text = replace_once(text,
'''        hookAfter(Application.class.getDeclaredMethod("onCreate"),\n                chain -> captureApplication(chain.getThisObject()));\n\n        hookAfter(InputMethodService.class.getDeclaredMethod("onCreate"),\n                chain -> captureIme(chain.getThisObject()));\n''',
'''        hookAfter(Application.class.getDeclaredMethod("onCreate"),\n                chain -> captureApplication(chain.getThisObject()));\n        hookAfter(Application.class.getDeclaredMethod("onConfigurationChanged", Configuration.class),\n                chain -> captureConfiguration(chain.getThisObject(), (Configuration) chain.getArg(0)));\n\n        hookAfter(InputMethodService.class.getDeclaredMethod("onCreate"),\n                chain -> captureIme(chain.getThisObject()));\n        hookAfter(InputMethodService.class.getDeclaredMethod("onConfigurationChanged", Configuration.class),\n                chain -> captureConfiguration(chain.getThisObject(), (Configuration) chain.getArg(0)));\n''',
    'configuration hooks')

text = replace_once(text,
'''        ensureConfigSync(app);\n    }\n\n    private static Activity findActivity(Context context) {\n''',
'''        ensureConfigSync(app);\n        refreshLiveNightMode(app.getResources().getConfiguration().uiMode, null);\n    }\n\n    private void captureConfiguration(Object object, Configuration configuration) {\n        if (!(object instanceof Context) || configuration == null) return;\n        Context context = (Context) object;\n        try {\n            if (!TARGET.equals(context.getPackageName())) return;\n        } catch (Throwable ignored) {\n            return;\n        }\n        refreshLiveNightMode(configuration.uiMode, null);\n    }\n\n    private static Activity findActivity(Context context) {\n''',
    'capture configuration')

text = replace_once(text,
'''        if (previousIme != ime) {\n            clearToolbarCarrierCache();\n            clearKeyboardHint();\n        }\n        imeRef = new WeakReference<>(ime);\n        ensureConfigSync(ime);\n''',
'''        if (previousIme != ime) {\n            clearToolbarCarrierCache();\n            clearKeyboardHint();\n            runtimeKeyboardRef = new WeakReference<>(null);\n            runtimeKeyboardState = null;\n        }\n        imeRef = new WeakReference<>(ime);\n        refreshLiveNightMode(ime.getResources().getConfiguration().uiMode, null);\n        ensureConfigSync(ime);\n''',
    'capture ime runtime reset')

old_intercept = '''    private Object interceptDispatchTouch(XposedInterface.Chain chain) throws Throwable {\n        Object target = chain.getThisObject();\n        Object eventObject = chain.getArg(0);\n        if (!(target instanceof View) || !(eventObject instanceof MotionEvent)) return chain.proceed();\n\n        View view = (View) target;\n        MotionEvent event = (MotionEvent) eventObject;\n\n        // This View.dispatchTouchEvent hook is the same proven chain used by the keyboard\n        // gesture feature. Run the hidden settings detector before filtering to keyboard views.\n        tryHandleEmbeddedSettingsUnlock(view, event);\n\n        Class<?> keyboardBase = keyboardBaseClass;\n\n        if (keyboardBase == null) {\n            if (event.getActionMasked() != MotionEvent.ACTION_DOWN) return chain.proceed();\n            keyboardBase = KeyboardCompat.findKeyboardBase(view.getClass());\n            if (keyboardBase == null) return chain.proceed();\n            keyboardBaseClass = keyboardBase;\n            logInfo("keyboard class cached: " + keyboardBase.getName());\n        } else if (!keyboardBase.isInstance(view)) {\n            return chain.proceed();\n        }\n\n        if (KeyboardCompat.isHandwritingContext(view)) {\n            tracker.clear(view);\n            view.post(() -> hideKeyboardHint(0L));\n            return chain.proceed();\n        }\n\n        ensureKeyboardLabelDrawHook(view.getClass(), view);\n        if (event.getActionMasked() == MotionEvent.ACTION_DOWN && !configBridge.isLoaded()) {\n            ensureConfigSync(view.getContext());\n        }\n        return interceptKeyboardTouch(chain, view, event);\n    }\n'''
new_intercept = '''    private Object interceptDispatchTouch(XposedInterface.Chain chain) throws Throwable {\n        Object target = chain.getThisObject();\n        Object eventObject = chain.getArg(0);\n        if (!(target instanceof View) || !(eventObject instanceof MotionEvent)) return chain.proceed();\n\n        View view = (View) target;\n        MotionEvent event = (MotionEvent) eventObject;\n        int actionMasked = event.getActionMasked();\n\n        if (actionMasked == MotionEvent.ACTION_UP) {\n            tryHandleEmbeddedSettingsUnlock(view, event);\n        }\n\n        Class<?> keyboardBase = keyboardBaseClass;\n        if (keyboardBase == null) {\n            if (actionMasked != MotionEvent.ACTION_DOWN) return chain.proceed();\n            keyboardBase = KeyboardCompat.findKeyboardBase(view.getClass());\n            if (keyboardBase == null) return chain.proceed();\n            keyboardBaseClass = keyboardBase;\n            logInfo("keyboard class cached: " + keyboardBase.getName());\n        } else if (!keyboardBase.isInstance(view)) {\n            return chain.proceed();\n        }\n\n        KeyboardRuntimeState runtime = runtimeStateFor(view);\n        if (runtime.handwriting) {\n            tracker.clear(view);\n            if (actionMasked == MotionEvent.ACTION_DOWN || actionMasked == MotionEvent.ACTION_UP) {\n                view.post(() -> hideKeyboardHint(0L));\n            }\n            return chain.proceed();\n        }\n\n        if (actionMasked == MotionEvent.ACTION_DOWN) {\n            maybeEnsureNativeSingleKeyDrawHooks(view);\n            ensureKeyboardLabelDrawHook(view.getClass(), view);\n            if (!configBridge.isLoaded()) ensureConfigSync(view.getContext());\n        }\n        return interceptKeyboardTouch(chain, view, event);\n    }\n\n    private KeyboardRuntimeState runtimeStateFor(View keyboard) {\n        View cachedView = runtimeKeyboardRef.get();\n        KeyboardRuntimeState cached = runtimeKeyboardState;\n        if (cachedView == keyboard && cached != null) return cached;\n        KeyboardRuntimeState resolved = KeyboardRuntimeState.from(keyboard);\n        runtimeKeyboardRef = new WeakReference<>(keyboard);\n        runtimeKeyboardState = resolved;\n        return resolved;\n    }\n\n    private void maybeEnsureNativeSingleKeyDrawHooks(View keyboard) {\n        if (nativeSingleKeyHooksResolved || keyboard == null) return;\n        long now = SystemClock.uptimeMillis();\n        if (now < nativeSingleKeyNextResolveAtMs) return;\n        nativeSingleKeyNextResolveAtMs = now + 2000L;\n        ensureNativeSingleKeyDrawHooks(keyboard);\n    }\n'''
text = replace_once(text, old_intercept, new_intercept, 'touch hot path')

old_hook = '''    private synchronized void ensureKeyboardLabelDrawHook(Class<?> keyboardClass, View keyboard) {\n        if (keyboardClass == null || keyboard == null) return;\n        ensureNativeSingleKeyDrawHooks(keyboard);\n        Method drawMethod = findKeyboardDrawMethod(keyboardClass, "onDraw");\n        if (drawMethod == null) drawMethod = findKeyboardDrawMethod(keyboardClass, "dispatchDraw");\n        if (drawMethod == null || keyboardLabelHookedMethods.putIfAbsent(drawMethod, Boolean.TRUE) != null) return;\n        try {\n            hookAfter(drawMethod, chain -> {\n                Object target = chain.getThisObject();\n                Object canvas = chain.getArg(0);\n                if (target instanceof View && canvas instanceof Canvas) {\n                    drawKeyboardFunctionLabels((View) target, (Canvas) canvas);\n                }\n            });\n            keyboard.postInvalidate();\n            logInfo("keyboard function-label draw hook installed for "\n                    + drawMethod.getDeclaringClass().getName() + '#' + drawMethod.getName());\n        } catch (Throwable throwable) {\n            keyboardLabelHookedMethods.remove(drawMethod);\n            logError("keyboard function-label draw hook failed", throwable);\n        }\n    }\n'''
new_hook = '''    private void ensureKeyboardLabelDrawHook(Class<?> keyboardClass, View keyboard) {\n        if (keyboardClass == null || keyboard == null\n                || keyboardDrawPreparedClasses.containsKey(keyboardClass)) return;\n        synchronized (this) {\n            if (keyboardDrawPreparedClasses.containsKey(keyboardClass)) return;\n            Method drawMethod = findKeyboardDrawMethod(keyboardClass, "onDraw");\n            if (drawMethod == null) drawMethod = findKeyboardDrawMethod(keyboardClass, "dispatchDraw");\n            if (drawMethod == null) {\n                keyboardDrawPreparedClasses.put(keyboardClass, Boolean.TRUE);\n                return;\n            }\n            if (keyboardLabelHookedMethods.putIfAbsent(drawMethod, Boolean.TRUE) != null) {\n                keyboardDrawPreparedClasses.put(keyboardClass, Boolean.TRUE);\n                return;\n            }\n            try {\n                hookAfter(drawMethod, chain -> {\n                    Object target = chain.getThisObject();\n                    Object canvas = chain.getArg(0);\n                    if (target instanceof View && canvas instanceof Canvas) {\n                        drawKeyboardFunctionLabels((View) target, (Canvas) canvas);\n                    }\n                });\n                keyboardDrawPreparedClasses.put(keyboardClass, Boolean.TRUE);\n                keyboard.postInvalidate();\n                logInfo("keyboard function-label draw hook installed for "\n                        + drawMethod.getDeclaringClass().getName() + '#' + drawMethod.getName());\n            } catch (Throwable throwable) {\n                keyboardLabelHookedMethods.remove(drawMethod);\n                logError("keyboard function-label draw hook failed", throwable);\n            }\n        }\n    }\n'''
text = replace_once(text, old_hook, new_hook, 'draw hook fast path')

text = replace_once(text,
'''        if (KeyboardCompat.isHandwritingContext(keyboard)) {\n            nativeSingleKeyLabelCache.remove(model);\n            return;\n        }\n''',
'''        if (runtimeStateFor(keyboard).handwriting) {\n            nativeSingleKeyLabelCache.remove(model);\n            return;\n        }\n''',
    'native handwriting cache')

text = replace_once(text,
'''        if (currentEditorPassword) return;\n        Config displayConfig = configBridge.current();\n        if (displayConfig == null || !displayConfig.showKeyLabels) return;\n        Config config = configBridge.current();\n        if (config == null || !config.hasAnyBinding() || !config.showKeyLabels) return;\n''',
'''        if (currentEditorPassword) return;\n        Config config = configBridge.current();\n        if (config == null || !config.hasAnyBinding() || !config.showKeyLabels) return;\n''',
    'single config read')

old_draw = '''    private void drawKeyboardFunctionLabels(View keyboard, Canvas canvas) {\n        if (keyboard == null || canvas == null || keyboard.getWidth() <= 0 || keyboard.getHeight() <= 0) return;\n        if (KeyboardCompat.isHandwritingContext(keyboard)) return;\n        Config config = configBridge.current();\n        if (config == null || !config.hasAnyBinding()) return;\n        try {\n            InputMethodService ime = imeRef.get();\n            EditorInfo editorInfo = ime == null ? null : ime.getCurrentInputEditorInfo();\n            if (editorInfo != null && isPassword(editorInfo.inputType)) return;\n\n            ensureNativeSingleKeyDrawHooks(keyboard);\n            if (nativeSingleKeyActiveKeyboardRef.get() == keyboard) return;\n\n            String name = keyboard.getClass().getName().toLowerCase(Locale.ROOT);\n            prepareKeyboardLabelPaint(keyboard);\n            if (name.contains("t9") || name.contains("nine")) {\n                drawT9FunctionLabels(keyboard, canvas, config);\n            } else if (name.contains("qwerty") || name.contains("wubi") || name.contains("pinyin")) {\n                ensureKeyboardLabelGeometry(keyboard);\n                drawQwertyFunctionLabels(keyboard, canvas, config);\n            }\n        } catch (Throwable throwable) {\n            logError("keyboard function-label drawing failed", throwable);\n        }\n    }\n'''
new_draw = '''    private void drawKeyboardFunctionLabels(View keyboard, Canvas canvas) {\n        if (keyboard == null || canvas == null || keyboard.getWidth() <= 0 || keyboard.getHeight() <= 0) return;\n        KeyboardRuntimeState runtime = runtimeStateFor(keyboard);\n        if (runtime.handwriting || currentEditorPassword) return;\n        Config config = configBridge.current();\n        if (config == null || !config.hasAnyBinding() || !config.showKeyLabels) return;\n        try {\n            if (nativeSingleKeyActiveKeyboardRef.get() == keyboard) return;\n            prepareKeyboardLabelPaint(keyboard);\n            if (runtime.mode == KeyboardRuntimeState.Mode.T9) {\n                drawT9FunctionLabels(keyboard, canvas, config);\n            } else if (runtime.mode == KeyboardRuntimeState.Mode.QWERTY) {\n                ensureKeyboardLabelGeometry(keyboard);\n                drawQwertyFunctionLabels(keyboard, canvas, config);\n            }\n        } catch (Throwable throwable) {\n            logError("keyboard function-label drawing failed", throwable);\n        }\n    }\n'''
text = replace_once(text, old_draw, new_draw, 'fallback draw hot path')

pattern = re.compile(r'''    private int resolveLiveNightMode\(View keyboard\) \{.*?\n    \}\n\n    private void prepareKeyboardLabelPaint''', re.S)
replacement = '''    private int resolveLiveNightMode(View keyboard) {\n        int cached = liveNightMode;\n        if (cached == Configuration.UI_MODE_NIGHT_NO\n                || cached == Configuration.UI_MODE_NIGHT_YES) return cached;\n        if (keyboard == null) return Configuration.UI_MODE_NIGHT_UNDEFINED;\n\n        int keyboardUiMode = Configuration.UI_MODE_NIGHT_UNDEFINED;\n        int applicationUiMode = Configuration.UI_MODE_NIGHT_UNDEFINED;\n        int imeUiMode = Configuration.UI_MODE_NIGHT_UNDEFINED;\n        try {\n            keyboardUiMode = keyboard.getResources().getConfiguration().uiMode;\n            Context application = keyboard.getContext().getApplicationContext();\n            if (application != null) applicationUiMode = application.getResources().getConfiguration().uiMode;\n        } catch (Throwable ignored) {}\n        InputMethodService ime = imeRef.get();\n        if (ime != null) {\n            try { imeUiMode = ime.getResources().getConfiguration().uiMode; } catch (Throwable ignored) {}\n        }\n        int resolved = KeyboardThemeState.resolveNightMode(keyboardUiMode, applicationUiMode, imeUiMode);\n        refreshLiveNightMode(resolved, keyboard);\n        return resolved;\n    }\n\n    private void refreshLiveNightMode(int uiMode, View sourceKeyboard) {\n        int resolved = KeyboardThemeState.resolveNightMode(\n                Configuration.UI_MODE_NIGHT_UNDEFINED, uiMode, Configuration.UI_MODE_NIGHT_UNDEFINED);\n        if (resolved != Configuration.UI_MODE_NIGHT_NO\n                && resolved != Configuration.UI_MODE_NIGHT_YES) return;\n        int previous = liveNightMode;\n        if (previous == resolved) return;\n        liveNightMode = resolved;\n        lastResolvedNightMode = resolved;\n        nativeSingleKeyPaintSignature = Long.MIN_VALUE;\n        View active = nativeSingleKeyActiveKeyboardRef.get();\n        if (active != null) active.postInvalidate();\n        View runtime = runtimeKeyboardRef.get();\n        if (runtime != null && runtime != active) runtime.postInvalidate();\n        if (sourceKeyboard != null && sourceKeyboard != active && sourceKeyboard != runtime) {\n            sourceKeyboard.postInvalidate();\n        }\n        if (previous != Configuration.UI_MODE_NIGHT_UNDEFINED) {\n            logInfo("keyboard label theme refreshed: " + previous + " -> " + resolved);\n        }\n    }\n\n    private void prepareKeyboardLabelPaint'''
text, count = pattern.subn(replacement, text, count=1)
if count != 1:
    raise SystemExit(f'resolveLiveNightMode: expected 1 replacement, found {count}')

MAIN.write_text(text, encoding='utf-8')

props = GRADLE.read_text(encoding='utf-8')
props = re.sub(r'^VERSION_CODE=.*$', 'VERSION_CODE=58', props, flags=re.M)
props = re.sub(r'^VERSION_NAME=.*$', 'VERSION_NAME=1.11.9-test3', props, flags=re.M)
GRADLE.write_text(props, encoding='utf-8')

RUNTIME.write_text('''package com.rww.wetypeswipe;\n\nimport android.view.View;\n\n/** Immutable per-active-keyboard classification used by touch and draw hot paths. */\nfinal class KeyboardRuntimeState {\n    enum Mode { QWERTY, T9, HANDWRITING, OTHER }\n\n    final Mode mode;\n    final boolean handwriting;\n\n    private KeyboardRuntimeState(Mode mode, boolean handwriting) {\n        this.mode = mode;\n        this.handwriting = handwriting;\n    }\n\n    static KeyboardRuntimeState from(View keyboard) {\n        if (keyboard == null) return new KeyboardRuntimeState(Mode.OTHER, false);\n        boolean handwriting = KeyboardCompat.isHandwritingContext(keyboard);\n        return classify(keyboard.getClass().getName(), handwriting);\n    }\n\n    static KeyboardRuntimeState classify(String className, boolean handwriting) {\n        if (handwriting) return new KeyboardRuntimeState(Mode.HANDWRITING, true);\n        String name = className == null ? "" : className.toLowerCase(java.util.Locale.ROOT);\n        if (name.contains("t9") || name.contains("nine")) {\n            return new KeyboardRuntimeState(Mode.T9, false);\n        }\n        if (name.contains("qwerty") || name.contains("wubi") || name.contains("pinyin")) {\n            return new KeyboardRuntimeState(Mode.QWERTY, false);\n        }\n        return new KeyboardRuntimeState(Mode.OTHER, false);\n    }\n}\n''', encoding='utf-8')

TEST.write_text('''package com.rww.wetypeswipe;\n\nimport static org.junit.Assert.assertEquals;\nimport static org.junit.Assert.assertFalse;\nimport static org.junit.Assert.assertTrue;\n\nimport org.junit.Test;\n\npublic class KeyboardRuntimeStateTest {\n    @Test public void classifiesQwertyOnce() {\n        KeyboardRuntimeState state = KeyboardRuntimeState.classify(\n                "com.tencent.wetype.keyboard.QwertyKeyboard", false);\n        assertEquals(KeyboardRuntimeState.Mode.QWERTY, state.mode);\n        assertFalse(state.handwriting);\n    }\n\n    @Test public void classifiesT9Once() {\n        KeyboardRuntimeState state = KeyboardRuntimeState.classify(\n                "com.tencent.wetype.keyboard.T9Keyboard", false);\n        assertEquals(KeyboardRuntimeState.Mode.T9, state.mode);\n    }\n\n    @Test public void handwritingOverridesKeyboardName() {\n        KeyboardRuntimeState state = KeyboardRuntimeState.classify(\n                "com.tencent.wetype.keyboard.QwertyKeyboard", true);\n        assertEquals(KeyboardRuntimeState.Mode.HANDWRITING, state.mode);\n        assertTrue(state.handwriting);\n    }\n\n    @Test public void unknownKeyboardIsOther() {\n        assertEquals(KeyboardRuntimeState.Mode.OTHER,\n                KeyboardRuntimeState.classify("x.y.CustomKeyboard", false).mode);\n    }\n}\n''', encoding='utf-8')

NOTES.write_text('''# v1.11.9-test3 性能优化测试\n\n基于 v1.11.9-test2，功能和配置语义不变。\n\n## 优化点\n- 键盘 View 首次识别后缓存 QWERTY/T9/手写模式，避免触摸和绘制热路径重复扫描父 View/类名。\n- 键盘绘制 Hook 按 Class 一次性准备，避免每次触摸进入 synchronized + 反射查找。\n- 原生单键 Hook 未就绪时改为 2 秒退避探测，不再每个触摸事件重复 Class/Method 查找。\n- fallback 绘制直接使用 currentEditorPassword，不再每帧调用 getCurrentInputEditorInfo。\n- 原生单键绘制只读取一次 Config。\n- 亮暗主题改为 Configuration 回调驱动缓存；正常单键绘制只做 volatile 主题读取，保留旧 View 配置兜底。\n- 隐藏设置五击检测仅在 ACTION_UP 进入。\n\n## 回归重点\n1. 26 键/九宫格下滑动作保持一致。\n2. 手写、数字、符号页不出现功能标签。\n3. 亮色↔暗色热切换仍即时刷新。\n4. 剪贴板、常用语、指定文本、输入法切换正常。\n5. 关于页 5 击设置正常。\n''', encoding='utf-8')

print('perf test3 patch applied')
