#!/usr/bin/env python3
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
def rep(path, old, new, count=1):
    text=path.read_text(encoding='utf-8'); n=text.count(old)
    if n < count: raise SystemExit(f'{path}: expected >= {count} match, got {n}')
    path.write_text(text.replace(old,new,count), encoding='utf-8')

p=ROOT/'app/src/main/java/com/rww/wetypeswipe/MainActivity.java'
rep(p,'import android.text.InputFilter;\n', 'import android.text.InputFilter;\nimport android.text.InputType;\n')
rep(p,'    private final String[] qwertyCustomLabels = new String[26];\n', '    private final String[] qwertyCustomLabels = new String[26];\n    private final String[] qwertyInsertTexts = new String[26];\n')
rep(p,'    private final String[] t9CustomLabels = new String[10];\n', '    private final String[] t9CustomLabels = new String[10];\n    private final String[] t9InsertTexts = new String[10];\n')
rep(p,'                    int action = Config.actionForMenuPosition(position);\n                    assignQwertyAction(key, action);\n                    dialog.dismiss();\n', '''                    int action = Config.actionForMenuPosition(position);\n                    dialog.dismiss();\n                    if (action == Config.ACTION_INSERT_TEXT) {\n                        int index = letter - 'a';\n                        showInsertTextDialog(Character.toUpperCase(letter) + " 键输入内容",\n                                qwertyInsertTexts[index], value -> {\n                                    assignQwertyAction(key, Config.ACTION_NONE);\n                                    qwertyInsertTexts[index] = value;\n                                    updateAllQwertyViews();\n                                });\n                    } else {\n                        assignQwertyAction(key, action);\n                    }\n''')
rep(p,'\n\n    private interface LabelValueChanged', '''\n\n    private interface TextValueChanged { void apply(String value); }\n\n    private void showInsertTextDialog(String title, String currentValue, TextValueChanged changed) {\n        EditText input = new EditText(this);\n        input.setText(Config.normalizeInsertedText(currentValue));\n        input.setHint("最多 1000 个字符，支持换行、符号和 Emoji");\n        input.setSingleLine(false);\n        input.setMinLines(3);\n        input.setMaxLines(8);\n        input.setGravity(Gravity.TOP | Gravity.START);\n        input.setInputType(InputType.TYPE_CLASS_TEXT | InputType.TYPE_TEXT_FLAG_MULTI_LINE\n                | InputType.TYPE_TEXT_FLAG_CAP_SENTENCES);\n        input.setFilters(new InputFilter[]{new InputFilter.LengthFilter(1000)});\n        LinearLayout host = vertical();\n        host.setPadding(dp(20), dp(8), dp(20), 0);\n        host.addView(input, new LinearLayout.LayoutParams(\n                ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT));\n        AlertDialog edit = new AlertDialog.Builder(this)\n                .setTitle(title)\n                .setView(host)\n                .setNegativeButton("取消", null)\n                .setPositiveButton("保存", null)\n                .create();\n        edit.setOnShowListener(ignored -> edit.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v -> {\n            String value = Config.normalizeInsertedText(input.getText().toString());\n            if (value.isEmpty()) {\n                Toast.makeText(this, "输入内容不能为空", Toast.LENGTH_SHORT).show();\n                return;\n            }\n            changed.apply(value);\n            edit.dismiss();\n        }));\n        edit.show();\n        input.requestFocus();\n        input.setSelection(input.length());\n    }\n\n    private interface LabelValueChanged''')
rep(p,'        for (int i = 0; i < qwertyKeys.length; i++) {\n            if (key.equals(qwertyKeys[i])) qwertyKeys[i] = "";\n        }\n', '        for (int i = 0; i < qwertyKeys.length; i++) {\n            if (key.equals(qwertyKeys[i])) qwertyKeys[i] = "";\n        }\n        int textIndex = key.charAt(0) - \'a\';\n        if (textIndex >= 0 && textIndex < qwertyInsertTexts.length) qwertyInsertTexts[textIndex] = "";\n')
rep(p,'        if (key == null || key.length() != 1) return Config.ACTION_NONE;\n        if (disabledKeys.indexOf(key) >= 0) return Config.ACTION_DISABLE;\n', '        if (key == null || key.length() != 1) return Config.ACTION_NONE;\n        int textIndex = key.charAt(0) - \'a\';\n        if (textIndex >= 0 && textIndex < qwertyInsertTexts.length\n                && !Config.normalizeInsertedText(qwertyInsertTexts[textIndex]).isEmpty()) return Config.ACTION_INSERT_TEXT;\n        if (disabledKeys.indexOf(key) >= 0) return Config.ACTION_DISABLE;\n')
rep(p,'                    t9Actions[digit] = Config.actionForMenuPosition(position);\n                    updateT9View(digit);\n                    dialog.dismiss();\n', '''                    int action = Config.actionForMenuPosition(position);\n                    dialog.dismiss();\n                    if (action == Config.ACTION_INSERT_TEXT) {\n                        showInsertTextDialog(Config.t9Label(digit) + " 输入内容", t9InsertTexts[digit], value -> {\n                            t9Actions[digit] = Config.ACTION_INSERT_TEXT;\n                            t9InsertTexts[digit] = value;\n                            updateT9View(digit);\n                        });\n                    } else {\n                        t9Actions[digit] = action;\n                        t9InsertTexts[digit] = "";\n                        updateT9View(digit);\n                    }\n''')
rep(p,'        Arrays.fill(qwertyKeys, "");\n        qwertyKeys[0] = "z";\n', '        Arrays.fill(qwertyKeys, "");\n        Arrays.fill(qwertyInsertTexts, "");\n        qwertyKeys[0] = "z";\n')
rep(p,'                    Arrays.fill(qwertyKeys, "");\n                    disabledKeys = "";\n', '                    Arrays.fill(qwertyKeys, "");\n                    Arrays.fill(qwertyInsertTexts, "");\n                    disabledKeys = "";\n')
rep(p,'                        t9Actions[digit] = Config.ACTION_NONE;\n                        updateT9View(digit);\n', '                        t9Actions[digit] = Config.ACTION_NONE;\n                        t9InsertTexts[digit] = "";\n                        updateT9View(digit);\n')
rep(p,'            qwertyCustomLabels[key - \'a\'] = Config.normalizeLabelValue(\n                    prefs.getString(Config.qwertyLabelPrefKey(key), ""));\n', '            qwertyCustomLabels[key - \'a\'] = Config.normalizeLabelValue(\n                    prefs.getString(Config.qwertyLabelPrefKey(key), ""));\n            qwertyInsertTexts[key - \'a\'] = Config.normalizeInsertedText(\n                    prefs.getString(Config.qwertyTextPrefKey(key), ""));\n')
rep(p,'            t9Actions[digit] = Config.validAction(\n                    prefs.getInt(Config.t9PrefKey(digit), Config.ACTION_NONE));\n', '            t9Actions[digit] = Config.validAction(\n                    prefs.getInt(Config.t9PrefKey(digit), Config.ACTION_NONE));\n            t9InsertTexts[digit] = Config.normalizeInsertedText(\n                    prefs.getString(Config.t9TextPrefKey(digit), ""));\n')
rep(p,'            editor.putString(Config.qwertyLabelPrefKey(key),\n                    Config.normalizeLabelValue(qwertyCustomLabels[key - \'a\']));\n', '            editor.putString(Config.qwertyLabelPrefKey(key),\n                    Config.normalizeLabelValue(qwertyCustomLabels[key - \'a\']));\n            editor.putString(Config.qwertyTextPrefKey(key),\n                    Config.normalizeInsertedText(qwertyInsertTexts[key - \'a\']));\n')
rep(p,'            editor.putString(Config.t9LabelPrefKey(digit),\n                    Config.normalizeLabelValue(t9CustomLabels[digit]));\n', '            editor.putString(Config.t9LabelPrefKey(digit),\n                    Config.normalizeLabelValue(t9CustomLabels[digit]));\n            editor.putString(Config.t9TextPrefKey(digit),\n                    Config.normalizeInsertedText(t9InsertTexts[digit]));\n')
rep(p,'            changed.putExtra(Config.qwertyLabelPrefKey(key),\n                    Config.normalizeLabelValue(qwertyCustomLabels[key - \'a\']));\n', '            changed.putExtra(Config.qwertyLabelPrefKey(key),\n                    Config.normalizeLabelValue(qwertyCustomLabels[key - \'a\']));\n            changed.putExtra(Config.qwertyTextPrefKey(key),\n                    Config.normalizeInsertedText(qwertyInsertTexts[key - \'a\']));\n')
rep(p,'            changed.putExtra(Config.t9LabelPrefKey(digit),\n                    Config.normalizeLabelValue(t9CustomLabels[digit]));\n', '            changed.putExtra(Config.t9LabelPrefKey(digit),\n                    Config.normalizeLabelValue(t9CustomLabels[digit]));\n            changed.putExtra(Config.t9TextPrefKey(digit),\n                    Config.normalizeInsertedText(t9InsertTexts[digit]));\n')
rep(p,'            case Config.ACTION_SELECT_TO_DOCUMENT_END: return "选文尾";\n', '            case Config.ACTION_SELECT_TO_DOCUMENT_END: return "选文尾";\n            case Config.ACTION_INSERT_TEXT: return "文本";\n')
rep(p,'v1.11.6-test4 · 关于图标五击内置设置','v1.11.6-test5 · 新增下滑输入指定内容')
print('Applied test5 standalone settings UI patch')
