#!/usr/bin/env python3
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
def rep(path, old, new, count=1):
    text=path.read_text(encoding='utf-8'); n=text.count(old)
    if n < count: raise SystemExit(f'{path}: expected >= {count} match, got {n}')
    path.write_text(text.replace(old,new,count), encoding='utf-8')

p=ROOT/'app/src/main/java/com/rww/wetypeswipe/EmbeddedSettingsUi.java'
rep(p,'import android.text.InputFilter;\n', 'import android.text.InputFilter;\nimport android.text.InputType;\n')
rep(p,'                    int action = Config.actionForMenuPosition(position);\n                    EmbeddedConfigEditor.assignQwerty(config, key, action);\n                    refreshQwerty();\n                    picker.dismiss();\n', '''                    int action = Config.actionForMenuPosition(position);\n                    picker.dismiss();\n                    if (action == Config.ACTION_INSERT_TEXT) {\n                        int index = letter - 'a';\n                        showInsertTextDialog(Character.toUpperCase(letter) + " 键输入内容",\n                                config.qwertyTexts[index], value -> {\n                                    EmbeddedConfigEditor.assignQwertyText(config, key, value);\n                                    refreshQwerty();\n                                });\n                    } else {\n                        EmbeddedConfigEditor.assignQwerty(config, key, action);\n                        refreshQwerty();\n                    }\n''')
rep(p,'                    config.t9Actions[digit] = Config.actionForMenuPosition(position);\n                    updateT9(digit);\n                    picker.dismiss();\n', '''                    int action = Config.actionForMenuPosition(position);\n                    picker.dismiss();\n                    if (action == Config.ACTION_INSERT_TEXT) {\n                        showInsertTextDialog(Config.t9Label(digit) + " 输入内容", config.t9Texts[digit], value -> {\n                            EmbeddedConfigEditor.assignT9Text(config, digit, value);\n                            updateT9(digit);\n                        });\n                    } else {\n                        config.t9Actions[digit] = action;\n                        EmbeddedConfigEditor.clearT9Text(config, digit);\n                        updateT9(digit);\n                    }\n''')
rep(p,'\n    private void showQwertyLabelDialog', '''\n    private interface TextChanged { void apply(String value); }\n\n    private void showInsertTextDialog(String title, String currentValue, TextChanged changed) {\n        EditText input = new EditText(activity);\n        input.setText(Config.normalizeInsertedText(currentValue));\n        input.setHint("最多 1000 个字符，支持换行、符号和 Emoji");\n        input.setSingleLine(false);\n        input.setMinLines(3);\n        input.setMaxLines(8);\n        input.setGravity(Gravity.TOP | Gravity.START);\n        input.setInputType(InputType.TYPE_CLASS_TEXT | InputType.TYPE_TEXT_FLAG_MULTI_LINE\n                | InputType.TYPE_TEXT_FLAG_CAP_SENTENCES);\n        input.setFilters(new InputFilter[]{new InputFilter.LengthFilter(1000)});\n        LinearLayout host = vertical();\n        host.setPadding(dp(activity, 20), dp(activity, 8), dp(activity, 20), 0);\n        host.addView(input);\n        AlertDialog edit = new AlertDialog.Builder(activity)\n                .setTitle(title)\n                .setView(host)\n                .setNegativeButton("取消", null)\n                .setPositiveButton("保存", null)\n                .create();\n        edit.setOnShowListener(ignored -> edit.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v -> {\n            String value = Config.normalizeInsertedText(input.getText().toString());\n            if (value.isEmpty()) {\n                Toast.makeText(activity, "输入内容不能为空", Toast.LENGTH_SHORT).show();\n                return;\n            }\n            changed.apply(value);\n            edit.dismiss();\n        }));\n        edit.show();\n        input.requestFocus();\n        input.setSelection(input.length());\n    }\n\n    private void showQwertyLabelDialog''')
rep(p,'v1.11.6-test4 · 内置模块模式','v1.11.6-test5 · 内置模块模式')
print('Applied test5 embedded settings UI patch')
